version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test123456
      - POSTGRES_USER=sadex_admin
      - POSTGRES_DB=kuepa_db
